// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0YzYM2SMNib_QNRiqnILXWqieKZrXjqQ',
    appId: '1:63717521520:android:ea9cd55abb1e2a866e5cb5',
    messagingSenderId: '63717521520',
    projectId: 'bookmycar-app',
    storageBucket: 'bookmycar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJqyEEOjscQ8gKXZoZWYGOiTUJH5N5FtQ',
    appId: '1:63717521520:ios:72ab508ad7e8697c6e5cb5',
    messagingSenderId: '63717521520',
    projectId: 'bookmycar-app',
    storageBucket: 'bookmycar-app.firebasestorage.app',
    androidClientId: '63717521520-ns94b16to8qrg8k1b7bapasigu7jqn7k.apps.googleusercontent.com',
    iosClientId: '63717521520-106sqh7ldjvng0thg07i23r81424vb87.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmycar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnmoEDuYaANSe4eO-2B4FUdW7-rJ5Ed_s',
    appId: '1:63717521520:web:aa90490a0238e5f56e5cb5',
    messagingSenderId: '63717521520',
    projectId: 'bookmycar-app',
    authDomain: 'bookmycar-app.firebaseapp.com',
    storageBucket: 'bookmycar-app.firebasestorage.app',
    measurementId: 'G-5VE99GRL4Z',
  );

}